permalink: /:year/:title
url: "http://localhost:9000"
baseurl: ""
show_drafts: true
future: true
limit_posts: 0
# Jekyll ignores dotfiles. Tell it not ignore this file
# which we need in order to prevent Github (hosting) run
# Jekyll against our build (we build it before deploying
# on our end)
include: [".nojekyll"]
markdown: kramdown
title: "Sergey Lukin, Web Developer"
description: "The personal website of web developer Sergey Lukin"
keywords: [web developer, PHP, Ruby, JavaScript, CSS, SEO, Unix, VIM, GIT, Apache]
author:
  name: Sergey Lukin
  email: contact@sergeylukin.com
  about: "I develop software. Most of the time I build stuff for Web. In my free time I read books from <a href=\"http://www.oreilly.com/\">O'Reilly</a>, watch screencasts from <a href=\"https://tutsplus.com/\">Tuts+</a>, <a href=\"https://upcase.com/\">Upcase</a>, <a href=\"http://www.pluralsight.com/\">PluralSight</a> and experiment with cutting edge technologies."
  GooglePlusID: 108108198145127769393
  profiles:
    - name: GitHub
      url: http://github.com/sergeylukin
      class: github
      data_icon: g
    - name: Email
      url: mailto:contact@sergeylukin.com
      class: email
      data_icon: "@"
    - name: Twitter
      url: https://twitter.com/sergey_lukin
      class: twitter
      data_icon: t
disqus:
  enabled: true
  shortname: sergeylukin
googleanalytics:
  account: UA-31126253-1
experiments:
  - title: CSS Skills Diagram
    sub_title: CSS/HTML
    description: Pure CSS responsive skills diagram
    url: http://sergeylukin.com/css-skills-diagram
    date: 2013-06-09
  - title: templatify-jQuery
    sub_title: Javascript
    description: Tiny HTML-replacement jQuery plugin
    url: https://github.com/sergeylukin/templatify
    date: 2012-04-19
  - title: CSS 3D Bar Graph
    sub_title: CSS/HTML
    description: Pure CSS 3D Bar Chart
    url: http://sergeylukin.com/css-3d-bar-graph
    date: 2012-03-19
  - title: CSS Jigsaw Puzzle piece
    sub_title: CSS/HTML
    description: Pure CSS jigsaw puzzle piece
    url: http://sergeylukin.com/css-jigsaw-puzzle-piece/
    date: 2012-02-19
  - title: CSS Stroked Cutaway Corner
    sub_title: CSS/HTML
    description: Pure CSS Stroked Cutaway Corner
    url: http://sergeylukin.com/css-stroked-cutaway-corner/
    date: 2012-02-19
  - title: CSS Pyramid Infographic
    sub_title: CSS/HTML
    description: Pure CSS Pyramid Infographic
    url: http://sergeylukin.com/css-pyramid-infographic/
    date: 2012-02-20
  - title: Dotfiles
    sub_title: Shell Scripts/VimL
    description: "unix dotfiles: zsh, git, vim, mutt, etc."
    url: https://github.com/sergeylukin/dotfiles
    date: 2012-02-19
  - title: OpenMVC
    sub_title: PHP
    description: Open Source MVC based PHP Framework
    url: https://github.com/openmvc
    date: 2011-03-29
